---
- hosts: centos
  become: true

  tasks:
    - name: Update all installed packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Reboot server
      ansible.builtin.reboot:                             
